package com.carstore.pojo;
// Generated Jun 5, 2018 6:27:59 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Faktura generated by hbm2java
 */
@Entity
@Table(name="faktura"
    ,catalog="carstore"
)
public class Faktura  implements java.io.Serializable {


     private Short fakturaId;
     private Samochod samochod;
     private Klient klient;
     private Pracownik pracownik;
     private Date dataSprzedazy;
     private String raty;

    public Faktura() {
    }

	
    public Faktura(Samochod samochod, Klient klient, Pracownik pracownik) {
        this.samochod = samochod;
        this.klient = klient;
        this.pracownik = pracownik;
    }
    public Faktura(Samochod samochod, Klient klient, Pracownik pracownik, Date dataSprzedazy, String raty) {
       this.samochod = samochod;
       this.klient = klient;
       this.pracownik = pracownik;
       this.dataSprzedazy = dataSprzedazy;
       this.raty = raty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fakturaID", unique=true, nullable=false)
    public Short getFakturaId() {
        return this.fakturaId;
    }
    
    public void setFakturaId(Short fakturaId) {
        this.fakturaId = fakturaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="samochodID", nullable=false)
    public Samochod getSamochod() {
        return this.samochod;
    }
    
    public void setSamochod(Samochod samochod) {
        this.samochod = samochod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="klientID", nullable=false)
    public Klient getKlient() {
        return this.klient;
    }
    
    public void setKlient(Klient klient) {
        this.klient = klient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pracownikID", nullable=false)
    public Pracownik getPracownik() {
        return this.pracownik;
    }
    
    public void setPracownik(Pracownik pracownik) {
        this.pracownik = pracownik;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_sprzedazy", length=10)
    public Date getDataSprzedazy() {
        return this.dataSprzedazy;
    }
    
    public void setDataSprzedazy(Date dataSprzedazy) {
        this.dataSprzedazy = dataSprzedazy;
    }

    
    @Column(name="raty", length=50)
    public String getRaty() {
        return this.raty;
    }
    
    public void setRaty(String raty) {
        this.raty = raty;
    }




}


