package com.carstore.pojo;
// Generated Jun 5, 2018 6:27:59 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kategorie generated by hbm2java
 */
@Entity
@Table(name="kategorie"
    ,catalog="carstore"
)
public class Kategorie  implements java.io.Serializable {


     private Short kategorieId;
     private String nazwaKategorii;
     private String uwagi;
     private String sportowy;
     private Set<Samochod> samochods = new HashSet<Samochod>(0);

    public Kategorie() {
    }

    public Kategorie(String nazwaKategorii, String uwagi, String sportowy, Set<Samochod> samochods) {
       this.nazwaKategorii = nazwaKategorii;
       this.uwagi = uwagi;
       this.sportowy = sportowy;
       this.samochods = samochods;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="kategorieID", unique=true, nullable=false)
    public Short getKategorieId() {
        return this.kategorieId;
    }
    
    public void setKategorieId(Short kategorieId) {
        this.kategorieId = kategorieId;
    }

    
    @Column(name="nazwa_kategorii", length=50)
    public String getNazwaKategorii() {
        return this.nazwaKategorii;
    }
    
    public void setNazwaKategorii(String nazwaKategorii) {
        this.nazwaKategorii = nazwaKategorii;
    }

    
    @Column(name="uwagi", length=65535)
    public String getUwagi() {
        return this.uwagi;
    }
    
    public void setUwagi(String uwagi) {
        this.uwagi = uwagi;
    }

    
    @Column(name="sportowy", length=50)
    public String getSportowy() {
        return this.sportowy;
    }
    
    public void setSportowy(String sportowy) {
        this.sportowy = sportowy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="kategorie")
    public Set<Samochod> getSamochods() {
        return this.samochods;
    }
    
    public void setSamochods(Set<Samochod> samochods) {
        this.samochods = samochods;
    }




}


