package com.carstore.pojo;
// Generated Jun 5, 2018 6:27:59 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Klient generated by hbm2java
 */
@Entity
@Table(name="klient"
    ,catalog="carstore"
)
public class Klient  implements java.io.Serializable {


     private Short klientId;
     private String imie;
     private String nazwisko;
     private String pesel;
     private String nrDowodu;
     private String ulica;
     private String nrTelefonu;
     private Set<Faktura> fakturas = new HashSet<Faktura>(0);

    public Klient() {
    }

    public Klient(String imie, String nazwisko, String pesel, String nrDowodu, String ulica, String nrTelefonu, Set<Faktura> fakturas) {
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.pesel = pesel;
       this.nrDowodu = nrDowodu;
       this.ulica = ulica;
       this.nrTelefonu = nrTelefonu;
       this.fakturas = fakturas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="klientID", unique=true, nullable=false)
    public Short getKlientId() {
        return this.klientId;
    }
    
    public void setKlientId(Short klientId) {
        this.klientId = klientId;
    }

    
    @Column(name="imie", length=50)
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }

    
    @Column(name="nazwisko", length=50)
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }

    
    @Column(name="pesel", length=50)
    public String getPesel() {
        return this.pesel;
    }
    
    public void setPesel(String pesel) {
        this.pesel = pesel;
    }

    
    @Column(name="nr_dowodu", length=50)
    public String getNrDowodu() {
        return this.nrDowodu;
    }
    
    public void setNrDowodu(String nrDowodu) {
        this.nrDowodu = nrDowodu;
    }

    
    @Column(name="ulica", length=50)
    public String getUlica() {
        return this.ulica;
    }
    
    public void setUlica(String ulica) {
        this.ulica = ulica;
    }

    
    @Column(name="nr_telefonu", length=50)
    public String getNrTelefonu() {
        return this.nrTelefonu;
    }
    
    public void setNrTelefonu(String nrTelefonu) {
        this.nrTelefonu = nrTelefonu;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="klient")
    public Set<Faktura> getFakturas() {
        return this.fakturas;
    }
    
    public void setFakturas(Set<Faktura> fakturas) {
        this.fakturas = fakturas;
    }




}


