package com.carstore.pojo;
// Generated Jun 5, 2018 6:27:59 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pracownik generated by hbm2java
 */
@Entity
@Table(name="pracownik"
    ,catalog="carstore"
)
public class Pracownik  implements java.io.Serializable {


     private Short pracownikId;
     private String imie;
     private String nazwisko;
     private String miasto;
     private String ulica;
     private String kodPocztowy;
     private String nrTelefonu;
     private Set<Faktura> fakturas = new HashSet<Faktura>(0);

    public Pracownik() {
    }

    public Pracownik(String imie, String nazwisko, String miasto, String ulica, String kodPocztowy, String nrTelefonu, Set<Faktura> fakturas) {
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.miasto = miasto;
       this.ulica = ulica;
       this.kodPocztowy = kodPocztowy;
       this.nrTelefonu = nrTelefonu;
       this.fakturas = fakturas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pracownikID", unique=true, nullable=false)
    public Short getPracownikId() {
        return this.pracownikId;
    }
    
    public void setPracownikId(Short pracownikId) {
        this.pracownikId = pracownikId;
    }

    
    @Column(name="imie", length=50)
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }

    
    @Column(name="nazwisko", length=50)
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }

    
    @Column(name="miasto", length=50)
    public String getMiasto() {
        return this.miasto;
    }
    
    public void setMiasto(String miasto) {
        this.miasto = miasto;
    }

    
    @Column(name="ulica", length=50)
    public String getUlica() {
        return this.ulica;
    }
    
    public void setUlica(String ulica) {
        this.ulica = ulica;
    }

    
    @Column(name="kod_pocztowy", length=50)
    public String getKodPocztowy() {
        return this.kodPocztowy;
    }
    
    public void setKodPocztowy(String kodPocztowy) {
        this.kodPocztowy = kodPocztowy;
    }

    
    @Column(name="nr_telefonu", length=50)
    public String getNrTelefonu() {
        return this.nrTelefonu;
    }
    
    public void setNrTelefonu(String nrTelefonu) {
        this.nrTelefonu = nrTelefonu;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pracownik")
    public Set<Faktura> getFakturas() {
        return this.fakturas;
    }
    
    public void setFakturas(Set<Faktura> fakturas) {
        this.fakturas = fakturas;
    }




}


